package com.example.demo.entities;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document("users")
public class User {
    @Id
    private String id; // auto-generated by MongoDB
    private String name;
    private String email;
    private String password;
    private String role;
    private String bio;
    private String createdAt;
    private String updatedAt;
}
