spring.application.name=Freelance_Backend_Development
server.port=${PORT:9090}
spring.mongodb.uri=mongodb+srv://Freelance-render:yuneth@labcluster.ce4ir9l.mongodb.net/freelanceDB?retryWrites=true&w=majority
spring.mongodb.database=freelanceDB
google.client-id=962166256032-k7ihoni7cj63qtmnbpqg8cs2b3sap5qn.apps.googleusercontent.com

