spring.application.name=Freelance_Backend_Development
server.port=${PORT:9090}

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}

google.client-id=${GOOGLE_CLIENT_ID:}
